micronaut:
  application:
    name: mqtt-adapter

mqtt-adapter:
  client-id: mqtt-adapter
  broker:
    address: 127.0.0.1
    port: 1883
  topics:
    - temperature
    - light
    - human
    - air-pressure-temperature
    - air-pressure
    - on-board-humidity
    - on-board-temperature